# Generated by Django 4.2.5 on 2023-09-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="название")),
            ],
            options={
                "verbose_name": "тэг",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10, verbose_name="номер")),
                ("name", models.CharField(max_length=150, verbose_name="название")),
                (
                    "solutions",
                    models.SmallIntegerField(verbose_name="количество решений"),
                ),
                ("difficulty", models.SmallIntegerField(verbose_name="сложность")),
                (
                    "tags",
                    models.ManyToManyField(related_name="теги", to="problems.tag"),
                ),
            ],
            options={
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
            },
        ),
    ]
