# Generated by Django 4.2.5 on 2023-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="number",
            field=models.CharField(max_length=10, unique=True, verbose_name="номер"),
        ),
    ]
