# Generated by Django 4.2.5 on 2023-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.IntegerField(verbose_name="сложность"),
        ),
        migrations.AlterField(
            model_name="problem",
            name="solutions",
            field=models.IntegerField(verbose_name="количество решений"),
        ),
    ]
