# Generated by Django 4.2.5 on 2023-09-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0004_alter_problem_difficulty_alter_problem_solutions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Belonging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problem",
                        verbose_name="задача",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.tag",
                        verbose_name="тэг",
                    ),
                ),
            ],
            options={
                "verbose_name": "принадлежность",
                "verbose_name_plural": "принадлежности",
            },
        ),
    ]
